### ISSUE TITLE
Same Issue as two previous users

### ISSUE THREAD

**Issue by jbower13** [MikeJSeo/SAM#12]
> library(shiny)
> runGitHub("SAM", "MikeJSeo")
> Downloading https://github.com/MikeJSeo/SAM/archive/master.tar.gz

Listening on http://127.0.0.1:3423
Error in source(file, ..., keep.source = TRUE, encoding = checkEncoding(file)) : 
  C:\Users\AppData\Local\Temp\RtmpegqnJG\shinyapp13803b113541\SAM-master/server.R:16:1: unexpected input
15:  
16: <<
    ^
In addition: Warning message:
In utils::download.file(url, ...) :
  downloaded length 1461120 != reported length 200

**Comment by LeanneLL** [comment]
Hello, have you solved the problem? I am having same issue
