### ISSUE TITLE
Issue when opening result.xlsx

### ISSUE THREAD

**Issue by yellow-sub** [MikeJSeo/SAM#14]
Thank you for this new SAM interface. I'm having issue after running SAM and exporting the results. The Excel file is damaged and can't be opened. What can I do to solve this problem?

**Comment by Lfreberg** [comment]
Okay, I'm happy to report that I DID manage to run my analysis by putting my datafile in the root directory. I'm not sure why I saw my root directory this time and not on my previous attempt, though. I did reboot, which often seems magical....Thanks, Mike! I'm on a tight deadline, so this was great!
