### ISSUE TITLE
Ingrid D

### ISSUE THREAD

**Issue by ingridkarolinska** [MikeJSeo/SAM#20]
Hi! 
When I start SAM i.e. write
runGitHub("SAM", "MikeJSeo")

I get the error-message 
Listening on http://127.0.0.1:3095
ERROR: [on_request_read] connection reset by peer

SAM seems to opens in Chrome but I cannot find or open any files for analysis. There does not seem to be any connection.

Any idea what is going on?
SAMR worked on my computer 6 month ago.
Ingrid

**Comment by LeanneLL** [comment]
Hello, have you solved the problem? I am having same issue
