### ISSUE TITLE
GSA Multiclass

### ISSUE THREAD

**Issue by rronen** [MikeJSeo/SAM#7]
Hi Mike,

Sorry to bombard you with questions, hopefully this is the last one for a while.

I've noticed that using GSA's `Multiclass` analysis, I only get back results where expression (x) is _correlated_ with the response (y) values. In other words, the order of the response {1,2,3,4,...} matters. 

This does not contradict the docs in any way (it mentions that positive results are those where higher expression correlates with higher values of the phenotype, etc.), however, I am wondering if there's a way to test the null of _any_ correlation between class and expression (i.e. class order 1,2,3,4,.. is meaningless, and could just as well reflect classes a,b,c,...).

Thanks!
Roy

**Comment by MikeJSeo** [comment]
As far as I know the order of 1,2,3,4 is meaningless and they are treated as factors. Whether you code it 1,2,3,4 or 1,3,2,4 should not change the result. I think the code below calculates the score and 1,2,3,4 are just used to indicate classes and there are no order constraint. 

multiclass.func <- function(x, y, s0 = 0) {
    ##assumes y is coded 1,2...
    nn <- table(y)
    m <- matrix(0, nrow = nrow(x), ncol = length(nn))
    v <- m
    for (j in 1:length(nn)) {
        m[, j] <- rowMeans(x[, y == j])
        v[, j] <- (nn[j] - 1) \* varr(x[, y == j], meanx = m[, 
            j])
    }
    mbar <- rowMeans(x)
    mm <- m - matrix(mbar, nrow = length(mbar), ncol = length(nn))
    fac <- (sum(nn)/prod(nn))
    scor <- sqrt(fac \* (apply(matrix(nn, nrow = nrow(m), ncol = ncol(m), 
        byrow = TRUE) \* mm \* mm, 1, sum)))
    sd <- sqrt(rowSums(v) \* (1/sum(nn - 1)) \* sum(1/nn))
    tt <- scor/(sd + s0)
    mm.stand = t(scale(t(mm), center = FALSE, scale = sd))
    return(list(tt = tt, numer = scor, sd = sd, stand.contrasts = mm.stand))
}

Mike

**Comment by rronen** [comment]
Mike, 

Thank you for the quick response.

Okay, got it. In that case, the following from the documentation might do with some clarification:

```
A “Negative” gene set is one in which lower expression of most genes in the gene set correlates
with higher values of the phenotype y.
```

At least for the case of `Multiclass`, saying `correlates with higher values of the phenotype y` may cause some confusion (it did for me).

Thanks again,
Roy
