### ISSUE TITLE
can't run SAM on my mac

### ISSUE THREAD

**Issue by hsinella** [MikeJSeo/SAM#8]
Hello, I tried to run SAM using mac (OSX Yosemite version 10.10.1). Everything worked find until I reach to this point

> library(shiny)
> runGitHub("SAM", "MikeJSeo")
> Downloading https://github.com/MikeJSeo/SAM/archive/master.tar.gz
> Error in runUrl(url, subdir = subdir, destdir = destdir, ...) : 
>   Failed to download URL https://github.com/MikeJSeo/SAM/archive/master.tar.gz
> In addition: Warning message:
> In download.file(url, method = method, ...) :
>   download had nonzero exit status

not sure what went wrong, can someone please help me?

thanks 

Ella

**Comment by LeanneLL** [comment]
Hello, have you solved the problem? I am having same issue.
